name: Discord Notify Fail

on:
  workflow_call:
    secrets:
        webhook_url:
          required: true
    inputs:
      message:
        required: false
        type: string
      name:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  notify:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Send Discord fail notification
        shell: bash
        run: |
          WEBHOOK_URL="${{ secrets.webhook_url }}"
          MSG="${{ inputs.message }}"
          NAME="${{ inputs.name }}"

          DEFAULT_MSG="❌ Deployment failed! Please check the logs."
          # Set defaults if inputs empty
          MSG=${MSG:-$DEFAULT_MSG}
          NAME=${NAME:-"GitHub Action Bot"}
          # Decide separator ? or &
          PARAMS="?with_components=true"
          if [[ "$WEBHOOK_URL" == *\?* ]]; then
            PARAMS="&with_components=true"
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"content\": \"$MSG\",
              \"username\": \"$NAME\",
              \"components\": [
                {
                  \"type\": 1,
                  \"components\": [
                    {
                      \"type\": 2,
                      \"style\": 5,
                      \"label\": \"View Workflow Run\",
                      \"url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
                    }
                  ]
                }
              ]
            }" \
            "$WEBHOOK_URL$PARAMS"
